# Data Concatenation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
training_data = pd.read_csv("data/Train.csv")
testing_data = pd.read_csv("data/Test.csv")

In [8]:
training_data

,Unnamed: 0,acc_max,gyro_max,acc_kurtosis,gyro_kurtosis,label,lin_max,acc_skewness,gyro_skewness,post_gyro_max,post_lin_max,fall
0,661,26.039919,7.309797,20.378162,2.782476,SDL,11.131080,3.891361,1.592927,7.086618,10.790400,1
1,122,25.864500,6.511954,14.187190,5.324864,FOL,7.945561,3.022175,2.376939,6.325522,7.719352,1
2,113,27.524501,12.944099,31.855926,22.891186,FOL,14.454818,4.849024,4.283890,12.888111,14.368784,1
3,14,30.647705,11.694868,23.608764,9.287735,FOL,15.228303,3.921537,2.794609,11.549971,14.944151,1
4,529,26.373917,11.168424,14.318453,15.983202,FKL,10.007396,3.087975,3.363557,11.057636,9.753058,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1423,1581,9.997262,0.039835,0.193545,0.022826,STD,0.053063,0.003216,0.132977,0.001416,0.002612,0
1424,1304,25.917910,11.347815,-0.996787,0.637958,JOG,16.898301,0.199294,0.808652,3.385675,1.724883,0
1425,778,12.098892,2.083724,1.745597,-0.874214,CSI,1.291914,-0.307109,0.424739,1.860753,0.861876,0
1426,1170,20.079536,4.770095,0.020741,-1.087583,STU,6.476275,0.344870,0.311172,0.243046,0.995053,0
1427,1670,9.956709,0.223359,1.165654,0.353090,STD,0.091898,-0.460094,1.170471,-0.197760,-0.020703,0

In [9]:
testing_data

,Unnamed: 0,acc_max,gyro_max,acc_kurtosis,gyro_kurtosis,label,lin_max,acc_skewness,gyro_skewness,post_gyro_max,post_lin_max,fall
0,9,28.055199,10.794617,21.334536,34.163811,FOL,13.880578,3.283404,4.577283,10.755339,13.762561,1
1,11,26.639681,8.785024,13.518671,12.812894,FOL,15.789372,3.301849,3.464729,8.277714,15.341656,1
2,19,25.045219,5.307413,21.603060,4.754182,FOL,11.592445,3.124714,2.268676,4.976134,11.303823,1
3,23,24.102184,8.929061,24.647657,18.595684,FOL,10.107835,4.522305,3.955288,8.719755,9.727437,1
4,28,31.668808,10.714750,18.008912,15.086251,FOL,14.138265,3.142132,3.530621,10.580791,13.935016,1
...,...,...,...,...,...,...,...,...,...,...,...,...
351,1760,20.882939,2.708036,2.619582,1.315623,WAL,6.399551,1.183977,1.023007,-0.778339,1.802209,0
352,1763,22.100430,3.427954,2.197909,0.420868,WAL,6.886338,1.212690,0.909372,0.358408,1.979209,0
353,1765,21.950314,4.113075,1.185087,-0.583776,WAL,5.659883,0.844756,0.404453,-0.207211,1.143965,0
354,1774,24.504250,6.026591,-0.663832,-0.563054,WAL,11.443950,0.264634,0.313140,1.058063,4.387827,0
355,1778,24.053077,3.656559,1.416664,-0.690195,WAL,8.623172,0.809532,0.272983,-0.301781,2.625933,0

In [20]:
training_data.shape

(1428, 12)

In [22]:
testing_data.shape

(356, 12)

#### Merging 2 dataframes

In [10]:
data = pd.merge(training_data, testing_data, how="outer")

In [11]:
data

,Unnamed: 0,acc_max,gyro_max,acc_kurtosis,gyro_kurtosis,label,lin_max,acc_skewness,gyro_skewness,post_gyro_max,post_lin_max,fall
0,661,26.039919,7.309797,20.378162,2.782476,SDL,11.131080,3.891361,1.592927,7.086618,10.790400,1
1,122,25.864500,6.511954,14.187190,5.324864,FOL,7.945561,3.022175,2.376939,6.325522,7.719352,1
2,113,27.524501,12.944099,31.855926,22.891186,FOL,14.454818,4.849024,4.283890,12.888111,14.368784,1
3,14,30.647705,11.694868,23.608764,9.287735,FOL,15.228303,3.921537,2.794609,11.549971,14.944151,1
4,529,26.373917,11.168424,14.318453,15.983202,FKL,10.007396,3.087975,3.363557,11.057636,9.753058,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1779,1760,20.882939,2.708036,2.619582,1.315623,WAL,6.399551,1.183977,1.023007,-0.778339,1.802209,0
1780,1763,22.100430,3.427954,2.197909,0.420868,WAL,6.886338,1.212690,0.909372,0.358408,1.979209,0
1781,1765,21.950314,4.113075,1.185087,-0.583776,WAL,5.659883,0.844756,0.404453,-0.207211,1.143965,0
1782,1774,24.504250,6.026591,-0.663832,-0.563054,WAL,11.443950,0.264634,0.313140,1.058063,4.387827,0
1783,1778,24.053077,3.656559,1.416664,-0.690195,WAL,8.623172,0.809532,0.272983,-0.301781,2.625933,0

In [12]:
1428+356

1784

In [13]:
# Dropping Unncessary Columns

In [25]:
data = data.drop(["Unnamed: 0"], axis=1)

In [26]:
data

,acc_max,gyro_max,acc_kurtosis,gyro_kurtosis,label,lin_max,acc_skewness,gyro_skewness,post_gyro_max,post_lin_max,fall
0,26.039919,7.309797,20.378162,2.782476,SDL,11.131080,3.891361,1.592927,7.086618,10.790400,1
1,25.864500,6.511954,14.187190,5.324864,FOL,7.945561,3.022175,2.376939,6.325522,7.719352,1
2,27.524501,12.944099,31.855926,22.891186,FOL,14.454818,4.849024,4.283890,12.888111,14.368784,1
3,30.647705,11.694868,23.608764,9.287735,FOL,15.228303,3.921537,2.794609,11.549971,14.944151,1
4,26.373917,11.168424,14.318453,15.983202,FKL,10.007396,3.087975,3.363557,11.057636,9.753058,1
...,...,...,...,...,...,...,...,...,...,...,...
1779,20.882939,2.708036,2.619582,1.315623,WAL,6.399551,1.183977,1.023007,-0.778339,1.802209,0
1780,22.100430,3.427954,2.197909,0.420868,WAL,6.886338,1.212690,0.909372,0.358408,1.979209,0
1781,21.950314,4.113075,1.185087,-0.583776,WAL,5.659883,0.844756,0.404453,-0.207211,1.143965,0
1782,24.504250,6.026591,-0.663832,-0.563054,WAL,11.443950,0.264634,0.313140,1.058063,4.387827,0
1783,24.053077,3.656559,1.416664,-0.690195,WAL,8.623172,0.809532,0.272983,-0.301781,2.625933,0

In [27]:
data.to_csv("data/patient_footfall.csv")

                                                    Completed